### ISSUE TITLE
idea: automatic dependencies bump

### ISSUE THREAD

**Issue by freitzzz** [palavrapasse/docs#91]
currently, we are bumping internal modules dependencies manually, which is a cumbersome manual process. let's automate this manual process!

**Comment by freitzzz** [comment]
https://itnext.io/keeping-software-dependencies-up-to-date-with-dependabot-79e0f17bcf18

**Comment by rutesantos4** [comment]
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
